services:
 http_client:
  class: \GuzzleHttp\Client

 twitter_api_collections_get_list:
  class: \NicolasMugnier\Twitter\Api\Collections\GetList
  arguments: ['@http_client']

 twitter_api_collections_get_show:
  class: \NicolasMugnier\Twitter\Api\Collections\GetShow
  arguments: ['@http_client']

 twitter_api_collections_post_create:
  class: \NicolasMugnier\Twitter\Api\Collections\PostCreate
  arguments: ['@http_client']

 twitter_api_collections_post_destroy:
  class: \NicolasMugnier\Twitter\Api\Collections\PostDestroy
  arguments: ['@http_client']

 twitter_api_collections_post_entries_add:
  class: \NicolasMugnier\Twitter\Api\Collections\PostEntriesAdd
  arguments: ['@http_client']

 twitter_api_friends_get_ids:
  class: \NicolasMugnier\Twitter\Api\Friends\GetIds
  arguments: ['@http_client']

 twitter_api_statuses_post_update:
  class: \NicolasMugnier\Twitter\Api\Statuses\PostUpdate
  arguments: ['@http_client']

 twitter_api_statuses_get_home_timeline:
  class: \NicolasMugnier\Twitter\Api\Statuses\GetHomeTimeLine
  arguments: ['@http_client']

 twitter_api_statuses_get_lookup:
  class: \NicolasMugnier\Twitter\Api\Statuses\GetLookup
  arguments: ['@http_client']

 twitter_api_statuses_get_user_timeline:
  class: \NicolasMugnier\Twitter\Api\Statuses\GetUserTimeLine
  arguments: ['@http_client']

 twitter_api_statuses_post_destroy:
  class: \NicolasMugnier\Twitter\Api\Statuses\PostDestroy
  arguments: ['@http_client']