imports:
  - { resource : ./parameters.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $oauthConsumerKey: '%twitter.api.oauth_consumer_key%'
      $oauthConsumerSecret: '%twitter.api.oauth_consumer_secret%'
      $oauthToken: '%twitter.api.oauth_token%'
      $oauthTokenSecret: '%twitter.api.oauth_token_secret%'
      $bearerToken: '%twitter.api.bearer_token%'
      $defaultVersion: '%twitter.api.default_version%'
      $defaultFormat: '%twitter.api.default_format%'
  
  GuzzleHttp\Client: ~

  NicolasMugnier\Twitter\Api\:
    resource: '../src/*'